### ISSUE TITLE
SLES 12 installation fails: ImportError: No module named glob

### ISSUE THREAD

**Issue by pleia2** [linux-on-ibm-z/PDS#52]
I was following the instructions for SLES 12, and when I get to the step instructing me to do "sudo pip install 'cryptography==1.4' Flask launchpadlib simplejson logging" the command ends with an error containing the following:

ERROR: Command errored out with exit status 1:
 command: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip-20.2.3-py2.7.egg/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpf3_NaV
     cwd: /tmp/pip-install-BdET9I/httplib2
Complete output (4 lines):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-20.2.3-py2.7.egg/pip/_vendor/pep517/_in_process.py", line 15, in <module>
    from glob import glob
ImportError: No module named glob

ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip-20.2.3-py2.7.egg/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpf3_NaV Check the logs for full command output.

I tried to remedy this, but Python 2.7 reached End of Life back in January, so the documentation for it is already starting to disappear and be supplanted by Python 3 documentation.

**Comment by cwsolee** [comment]
We tried on SLES 12 SP5 and seems ok, what version of SLES 12 are u using? We'll change our doc to reflect that too.

**Comment by pleia2** [comment]
This is a SLES SP3 system, but if it works in SP5 it must just be a dependency problem, do you know what pip (or zypper package) is providing the glob module?

**Comment by pleia2** [comment]
Python 2 issue, closing out since we've moved to Python 3.
